import { useEffect, useState } from 'react'
import { ArrowRight, BarChart3, Check, ChevronRight, CloudUpload, FileText, GraduationCap, Headphones, Home, Landmark, List, Mail, MapPin, Menu, Monitor, Phone as PhoneIcon, Settings, ShieldCheck, Smartphone, Tag, Users, X, Zap } from 'lucide-react'
import './App.css'

const nav = [
  ['Home', '/', Home], ['Features', '/#features', List], ['How It Works', '/#how-it-works', Settings],
  ['Pricing', '/#pricing', Tag], ['About', '/#about', Users], ['Contact', '/#contact', Mail],
]
const legal = [['Privacy Policy', '/privacy-policy'], ['Terms of Use', '/terms-of-use'], ['Delete Account', '/delete-account'], ['Sitemap.xml', '/sitemap.xml']]
const features = [
  ['Manage Clearances', 'Create and customize clearance processes with multiple departments.', FileText, 'purple'],
  ['Document Verification', 'Students upload and track their documents in real time.', CloudUpload, 'blue'],
  ['Multi-Role Approvals', 'Empower staff to review, approve or reject documents easily.', Users, 'pink'],
  ['Real-Time Reports', 'Get insights and export detailed clearance reports.', BarChart3, 'orange'],
  ['Secure & Reliable', 'Your data is encrypted and always protected.', ShieldCheck, 'green'],
  ['Web & Mobile Access', 'Access from anywhere on web or mobile app.', Monitor, 'purple'],
]
const stats = [['50+', 'Institutions (Target)', Landmark], ['100,000+', 'Students (Target)', Users], ['99.9%', 'Uptime & Security', ShieldCheck], ['24/7', 'Support', Headphones]]
const steps = [
  ['Set Up Your Institution', 'Create departments, clearance requirements and approval workflows.'],
  ['Students Submit Documents', 'Students upload their documents and track their clearance progress in real time.'],
  ['Review, Approve & Complete', 'Staff review and approve documents. Students get notified at every step.'],
]
const plans = [
  ['Starter', 'Up to 500 active students', 25, ['Clearance workflows', 'Document verification', 'Email support']],
  ['Standard', 'Up to 2,500 active students', 60, ['Everything in Starter', 'Staff approval roles', 'Progress reports']],
  ['Pro', 'Up to 10,000 active students', 120, ['Everything in Standard', 'Advanced reporting', 'Priority support']],
  ['Enterprise', '10,000+ active students', 250, ['Everything in Pro', 'Institution-wide scale', 'Dedicated onboarding']],
]
const contact = { email: import.meta.env.VITE_CONTACT_EMAIL || 'thegideons.2.5.1@gmail.com', phone: import.meta.env.VITE_CONTACT_PHONE || '', office: import.meta.env.VITE_CONTACT_OFFICE || '' }

function Brand({ compact = false }) { return <a className={`brand ${compact ? 'brand-compact' : ''}`} href="/" aria-label="ClearanceLink home"><span className="brand-mark"><img src="/logo-transparent.png" alt="" /></span><span className="brand-word"><img src="/logo-transparent.png" alt="" /></span></a> }
function Socials() { return <div className="socials" aria-label="Social media">{['facebook','x','instagram','linkedin','youtube'].map(name => <span key={name} aria-label={name}><img src={`/brands/${name}.svg`} alt={name} /></span>)}</div> }
function Header() {
  const [open, setOpen] = useState(false)
  useEffect(() => { const onKey = e => { if (e.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', onKey); document.body.style.overflow = open ? 'hidden' : ''; return () => { window.removeEventListener('keydown', onKey); document.body.style.overflow = '' } }, [open])
  return <><header className="site-header"><div className="header-inner container"><Brand /><button className="menu-button" onClick={() => setOpen(true)} aria-label="Open menu" aria-expanded={open}><Menu /></button></div></header><div className={`drawer-backdrop ${open ? 'is-open' : ''}`} onClick={() => setOpen(false)} /><aside className={`drawer ${open ? 'is-open' : ''}`} aria-label="Site navigation" aria-hidden={!open}><div className="drawer-top"><Brand compact /><button className="drawer-close" onClick={() => setOpen(false)} aria-label="Close menu"><X /></button></div><nav className="drawer-nav">{nav.map(([label, href, Icon]) => <a key={label} href={href} className={location.pathname === '/' && ((location.hash || '/') === href || (href === '/' && !location.hash)) ? 'active' : ''} onClick={() => setOpen(false)}><Icon size={21} /><span>{label}</span></a>)}</nav><div className="drawer-bottom"><div className="drawer-legal">{legal.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</div><Socials /></div></aside></>
}
function StoreBadges() { return <div className="store-badges"><a href="#contact" className="store-badge" aria-label="Ask about App Store availability"><img className="store-logo" src="/brands/apple.svg" alt="" /><span><small>Download on the</small><strong>App Store</strong></span></a><a href="#contact" className="store-badge" aria-label="Ask about Google Play availability"><img className="store-logo" src="/brands/googleplay.svg" alt="" /><span><small>GET IT ON</small><strong>Google Play</strong></span></a></div> }
function Phone() { return <div className="phone" aria-label="ClearanceLink app demo"><div className="phone-side" /><div className="phone-screen"><video autoPlay muted loop playsInline preload="metadata" aria-label="ClearanceLink app screen recording"><source src="/videos/clearancelink-demo.mp4" type="video/mp4" /></video></div></div> }
function Dashboard() { return <div className="laptop" aria-label="ClearanceLink dashboard illustration"><div className="laptop-screen"><div className="dash-sidebar"><b>✦ Clearance<span>Link</span></b>{['Dashboard', 'Students', 'Clearance Setup', 'Departments', 'Approvals', 'Documents', 'Reports', 'Settings'].map((item, i) => <div className={i === 0 ? 'selected' : ''} key={item}><span>▦</span>{item}</div>)}</div><div className="dash-main"><div className="dash-top"><span>2025/2026⌄</span><span>♧　Admin⌄</span></div><h3>Dashboard</h3><div className="dash-metrics">{[['Total Students','4,382'],['Cleared','3,127'],['Pending','1,255'],['In Review','239']].map(([label,value],i) => <div key={label}><small>{label}</small><strong className={['','green','orange','purple'][i]}>{value}</strong></div>)}</div><div className="dash-panels"><div><b>Clearance Progress</b><div className="donut"><span><strong>72%</strong><small>Completed</small></span></div><p>● Cleared　 ● Pending　 ● In Review</p></div><div><b>Recent Activities</b><p>🟢 Document approved</p><p>🔴 Document rejected</p><p>🟣 Clearance completed</p></div></div></div></div><div className="laptop-base" /></div> }
function Hero() { return <section id="home" className="hero-section"><div className="container hero-layout"><div className="hero-copy"><div className="eyebrow"><GraduationCap size={18} /> Digital Clearance for Modern Institutions</div><h1>Simplify Student<br />Clearance, <span>Go Digital<br />with Confidence</span></h1><p>ClearanceLink helps educational institutions manage student clearance, document verification, staff approvals and overall clearance progress — all in one secure, modern platform.</p><StoreBadges /><div className="benefits"><span><ShieldCheck />Secure</span><span><Zap />Fast</span><span><Smartphone />Web &amp; Mobile</span></div></div><div className="product-display"><div className="hero-orbit" /><Dashboard /><Phone /></div></div></section> }
function Heading({ kicker, title, description }) { return <div className="section-heading"><span className="section-kicker">{kicker}</span><h2>{title}</h2><p>{description}</p></div> }
function Features() { return <section id="features" className="section features-section container"><Heading kicker="FEATURES" title={<>Powerful Features<br />for Modern Institutions</>} description="Everything you need to manage student clearance efficiently." /><div className="feature-grid">{features.map(([title, body, Icon, tone]) => <article className="feature-card" key={title}><span className={`feature-icon tone-${tone}`}><Icon size={29} strokeWidth={2.5} /></span><div><h3>{title}</h3><p>{body}</p></div><ChevronRight className="feature-chevron" size={18} /></article>)}</div></section> }
function Statistics() { return <div className="stats-grid">{stats.map(([value, label, Icon]) => <div className="stat" key={label}><Icon size={34} /><div><strong>{value}</strong><span>{label}</span></div></div>)}</div> }
function HowItWorks() { return <section id="how-it-works" className="section steps-section"><div className="container"><Heading kicker="HOW IT WORKS" title="Get Started in 3 Simple Steps" description="From setup to full clearance management in minutes." /><div className="steps-grid">{steps.map(([title, body], i) => <div className="step-wrap" key={title}><article className="step-card"><span className="step-number">{i + 1}</span><div><h3>{title}</h3><p>{body}</p></div></article>{i < 2 && <ArrowRight className="step-arrow" />}</div>)}</div></div></section> }
function Pricing() { const [billing, setBilling] = useState('monthly'); return <section id="pricing" className="section pricing-section container"><Heading kicker="PRICING" title="Simple, Transparent Pricing" description="Choose a plan that fits your institution’s needs." /><div className="billing-toggle" aria-label="Billing period"><button className={billing === 'monthly' ? 'selected' : ''} onClick={() => setBilling('monthly')} aria-pressed={billing === 'monthly'}>Monthly</button><button className={billing === 'annual' ? 'selected' : ''} onClick={() => setBilling('annual')} aria-pressed={billing === 'annual'}>Annual</button></div><p className="billing-note">Save 20% with annual billing.</p><div className="pricing-grid">{plans.map(([name, limit, monthly, benefits]) => <article className="price-card" key={name}><h3>{name}</h3><p>{limit}</p><div className="price">{name === 'Enterprise' && <small>From </small>}${(billing === 'annual' ? Math.round(monthly * 12 * .8) : monthly).toLocaleString()}<span>/{billing === 'annual' ? 'year' : 'month'}</span></div><ul>{benefits.map(benefit => <li key={benefit}><Check size={17} />{benefit}</li>)}</ul><a className="primary-link" href="#contact">Get Started</a></article>)}</div></section> }
function About() { return <section id="about" className="section about-section"><div className="container about-layout"><div className="about-copy"><span className="section-kicker">ABOUT US</span><h2>Empowering Institutions Through <span>Digital Solutions</span></h2><p>ClearanceLink is built to simplify student clearance, improve efficiency and enhance transparency in educational institutions. Our mission is to provide a secure, reliable and modern platform for institutions to manage clearance processes with ease.</p><Statistics /></div><div className="about-visual"><img src="/campus-footer.png" alt="Illustration of an educational institution" /></div></div></section> }
function Contact() { const [values,setValues] = useState({name:'',email:'',message:''}); const [error,setError] = useState(''); const [opened,setOpened] = useState(false); const update = key => e => { setValues({...values,[key]:e.target.value}); setError(''); setOpened(false) }; const submit = e => { e.preventDefault(); if (!values.name.trim() || !values.email.trim() || !values.message.trim()) return setError('Please complete all fields.'); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim())) return setError('Enter a valid email address.'); if (!contact.email) return setError('Message delivery is not configured yet.'); window.location.href = `mailto:${contact.email}?subject=${encodeURIComponent(`ClearanceLink enquiry from ${values.name.trim()}`)}&body=${encodeURIComponent(`${values.message.trim()}\n\nFrom: ${values.name.trim()} <${values.email.trim()}>`)}`; setOpened(true) }; return <section id="contact" className="section contact-section container"><Heading kicker="CONTACT US" title="Get in Touch" description={<>Have questions or need support?<br />We’re here to help.</>} /><div className="contact-layout"><form className="contact-form" onSubmit={submit} noValidate><label><span>Name</span><div className="input-wrap"><Users size={18} /><input value={values.name} onChange={update('name')} autoComplete="name" placeholder="Your name" /></div></label><label><span>Email Address</span><div className="input-wrap"><Mail size={18} /><input value={values.email} onChange={update('email')} type="email" autoComplete="email" placeholder="you@institution.edu" /></div></label><label><span>Message</span><div className="input-wrap textarea-wrap"><FileText size={18} /><textarea value={values.message} onChange={update('message')} rows="5" placeholder="How can we help?" /></div></label>{error && <p className="form-error" role="alert">{error}</p>}{opened && <p className="form-success" role="status">Your email app is opening with your message ready to send.</p>}<button className="primary-link" type="submit">Send Message</button></form><div className="contact-cards"><div><span><Mail /></span><p><strong>Email Us</strong>{contact.email ? <a href={`mailto:${contact.email}`}>{contact.email}</a> : <small>Contact details coming soon</small>}</p></div><div><span><PhoneIcon /></span><p><strong>Call Us</strong>{contact.phone ? <a href={`tel:${contact.phone}`}>{contact.phone}</a> : <small>Contact details coming soon</small>}</p></div><div><span><MapPin /></span><p><strong>Our Office</strong><small>{contact.office || 'Contact details coming soon'}</small></p></div></div></div></section> }
function Footer() { return <footer className="site-footer"><div className="container footer-main"><div className="footer-brand"><Brand compact /><p>Digital clearance management for modern educational institutions. Secure, simple and efficient.</p></div><div className="footer-links">{legal.map(([label,href]) => <a href={href} key={label}>{label}</a>)}</div><Socials /></div><div className="container copyright">© 2026 ClearanceLink. All rights reserved.</div></footer> }
const legalContent = {
  '/privacy-policy': ['Privacy Policy', 'We respect the privacy of institutions, students and staff who use ClearanceLink.', [['Information we collect', 'ClearanceLink may process account details, institution information, documents and activity needed to provide the service.'], ['How information is used', 'Information is used to operate clearance workflows, verify submissions, communicate updates and maintain security.'], ['Your choices', 'Contact your institution administrator for access or correction requests. For website enquiries, use the contact form.']]],
  '/terms-of-use': ['Terms of Use', 'These terms describe the general conditions for using ClearanceLink.', [['Use of the service', 'Use ClearanceLink only for authorized institutional clearance activities.'], ['Institution responsibilities', 'Institutions manage their users, clearance requirements and the information they upload.'], ['Service availability', 'Features and availability may change as the platform develops.']]],
  '/delete-account': ['Delete Account', 'You can request deletion of your ClearanceLink account and associated personal information.', [['Request deletion', 'Contact your institution administrator or use the website contact form to request account deletion. Include the email address associated with the account.'], ['What happens next', 'We will confirm your identity and explain what can be deleted, including any records the institution must retain.']]],
}
function LegalPage({ path }) { const [title,intro,sections] = legalContent[path]; return <><Header /><main className="legal-page container"><span className="section-kicker">CLEARANCELINK</span><h1>{title}</h1><p className="legal-intro">{intro}</p>{sections.map(([heading,text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<a href="/" className="legal-back">← Back to home</a></main><Footer /></> }
export default function App() { const path = location.pathname.replace(/\/$/, '') || '/'; useEffect(() => { if (location.hash) setTimeout(() => document.querySelector(location.hash)?.scrollIntoView(), 50); if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const elements = document.querySelectorAll('.section-heading,.feature-card,.trust-strip,.step-card,.price-card,.about-copy,.about-visual,.contact-form,.contact-cards>div'); const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.target.classList.toggle('is-visible', entry.isIntersecting)), { threshold: 0.12, rootMargin: '0px 0px -5% 0px' }); elements.forEach(element => { element.classList.add('reveal'); observer.observe(element) }); return () => observer.disconnect() }, []); if (legalContent[path]) return <LegalPage path={path} />; return <><Header /><main><Hero /><Features /><div className="container trust-strip"><Statistics /><div className="trusted-label">Trusted by Institutions <small>Institution partnerships in progress</small></div></div><HowItWorks /><Pricing /><About /><Contact /></main><Footer /></> }
